### ISSUE TITLE
Update PyPI package

### ISSUE THREAD

**Issue by priiduonu** [gisce/markdown-blockdiag#10]
Please update the `markdown-blockdiag` on PyPI also. And thanks for the nice package!

**Comment by ecarreras** [comment]
Done! Thank you.
In theory we have [autodeploy to pypi](https://github.com/gisce/markdown-blockdiag/blob/master/.travis.yml#L13) when a tag is pushed with Travis-CI, but seems there is a problem.

**Comment by priiduonu** [comment]
Have you tried adding `sudo: required` to the `.travis.yml`?
